[project]
name = "simple_rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "langchain>=0.3.26",
    "ollama>=0.5.1",
    "qdrant-client>=1.15.0",
    "sentence-transformers>=5.0.0",
]
